name: Manual Approval Template

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      requestor:
        required: true
        type: string

jobs:
  
  print-details:
    runs-on: [self-hosted, Windows]
    steps:
      - name: Display Deployment Details
        shell: powershell
        run: |
          Write-Host "Requested By: ${{ inputs.requestor }}"
          Write-Host "Target Environment: ${{ inputs.environment }}"

  
  wait-for-approval:
    needs: print-details
    runs-on: [self-hosted, Windows]
    environment: ${{ inputs.environment }} # Ye line GitHub par "Approve/Reject" ka button dikhayegi
    steps:
      - name: Approved
        shell: powershell
        run: Write-Host "Approval received for ${{ inputs.environment }}!"
