name: Manual Approval Template

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      requestor:
        required: true
        type: string

jobs:
  print-details:
    runs-on: [self-hosted, Windows]
    steps:
      - name: Display Deployment Details
        shell: powershell
        run: |
          Write-Host "Requested By: ${{ inputs.requestor }}"
          Write-Host "Target Environment: ${{ inputs.environment }}"

 
  call-approval:
    needs: print-details  
    uses: Aayu1983/centeral-repo/.github/workflows/approval-template.yml@main
    with:
      environment: ${{ inputs.environment }}
