name: Terraform-Template-Multi-ENV

on:
  workflow_call:
    inputs:
      environment: { required: true, type: string }
      working_directory: { required: false, type: string, default: '.' } 
      tf_state_key: { required: true, type: string }
    secrets:
      client_id: { required: true }
      subscription_id: { required: true }
      tenant_id: { required: true }
      resource_group_name: { required: true }
      storage_account_name: { required: true }
      container_name: { required: true }

jobs:
  setup:
    name: "Init - ${{ inputs.environment }}"
    runs-on: [self-hosted, Windows]
    outputs:
      selected_branch: ${{ steps.branch_logic.outputs.branch }}
    steps:
      - name: Determine Branch Mapping
        id: branch_logic
        shell: powershell
        run: |           
            $envInput = "${{ inputs.environment }}".ToLower()
            $actualBranch = "${{ github.ref_name }}".ToLower()                
            $expectedBranch = if ($envInput -match "production|drhub") { "main" } else { $envInput }
              Write-Host "Checking: Environment [$envInput] needs Branch [$expectedBranch]. You are on [$actualBranch]."
             
               if ($actualBranch -ne $expectedBranch) {
               Write-Host "::error::VALIDATION FAILED! Cannot run $envInput from $actualBranch branch."               exit 1
              }      
              Write-Host "SUCCESS: Deployment Allowed."
              "branch=$expectedBranch" >> $env:GITHUB_OUTPUT
          
          
  infrastructure-validation:
    needs: setup
    environment: ${{ inputs.environment }}-plan
    runs-on: [self-hosted, Windows]
    outputs:
      plan_sha: ${{ steps.get_sha.outputs.sha }}
    defaults:
      run:
        shell: powershell
        working-directory: ${{ inputs.working_directory }}
    steps:
      - uses: actions/checkout@v4
        with:
          repository: ${{ github.repository }}
          ref: ${{ needs.setup.outputs.selected_branch }}

      - id: get_sha
        run: |
          $sha = (git rev-parse HEAD).Trim()
          "sha=$sha" >> $env:GITHUB_OUTPUT

      - uses: azure/login@v2
        with:
          client-id: ${{ secrets.client_id }}
          tenant-id: ${{ secrets.tenant_id }}
          subscription-id: ${{ secrets.subscription_id }}

      - name: Terraform Init & Plan
        env:
          ARM_CLIENT_ID: ${{ secrets.client_id }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.subscription_id }}
          ARM_TENANT_ID: ${{ secrets.tenant_id }}
          ARM_USE_OIDC: true
        run: |
          terraform init `
           -backend-config="resource_group_name=${{ secrets.client_id }}" `
           -backend-config="storage_account_name=${{ secrets.storage_account_name }}" `
           -backend-config="container_name=${{ secrets.container_name }}" `           
           -backend-config="use_azuread_auth=true" `
           -reconfigure
            
          terraform plan -out=tfplan -input=false

      - uses: actions/upload-artifact@v4
        with:
          name: tf-bin-${{ inputs.environment }}
          path: ${{ inputs.working_directory }}/tfplan
          retention-days: 1

  deployment-gatekeeper:
    needs: [setup, infrastructure-validation]
    uses: ./.github/workflows/approval-template.yml
    with:
      environment: ${{ inputs.environment }}
      requestor: ${{ github.actor }}
    secrets: inherit

  infrastructure-deployment:
    needs: [infrastructure-validation, deployment-gatekeeper]
    runs-on: [self-hosted, Windows]
    environment: ${{ inputs.environment }}
    defaults:
      run:
        shell: powershell
        working-directory: ${{ inputs.working_directory }}
    steps:
      - uses: actions/checkout@v4
        with:
          repository: ${{ github.repository }}
          ref: ${{ needs.infrastructure-validation.outputs.plan_sha }}

      - uses: actions/download-artifact@v4
        with:
          name: tf-bin-${{ inputs.environment }}
          path: ${{ inputs.working_directory }}

      - uses: azure/login@v2
        with:
          client-id: ${{ secrets.client_id }}
          tenant-id: ${{ secrets.tenant_id }}
          subscription-id: ${{ secrets.subscription_id }}

      - name: Terraform Apply
        env:
          ARM_CLIENT_ID: ${{ secrets.client_id }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.subscription_id }}
          ARM_TENANT_ID: ${{ secrets.tenant_id }}
          ARM_USE_OIDC: true
        run: |
          terraform init -backend=false # Fast init for apply
          terraform apply -auto-approve tfplan
